Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# score on train and test
print(f'Train Score: {pipe.score(X_train, y_train)}')
print(f'Test Score: {pipe.score(X_test, y_test)}')
------------------


[0;31m-------------------------------------------------------[0m
[0;31mIndexError[0m            Traceback (most recent call last)
File [0;32m/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/utils/_available_if.py:29[0m, in [0;36m_AvailableIfDescriptor._check[0;34m(self, obj, owner)[0m
[1;32m     28[0m [38;5;28;01mtry[39;00m:
[0;32m---> 29[0m     check_result [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mcheck[49m[43m([49m[43mobj[49m[43m)[49m
[1;32m     30[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m [38;5;28;01mas[39;00m e:

File [0;32m/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/pipeline.py:51[0m, in [0;36m_final_estimator_has.<locals>.check[0;34m(self)[0m
[1;32m     49[0m [38;5;28;01mdef[39;00m [38;5;21mcheck[39m([38;5;28mself[39m):
[1;32m     50[0m     [38;5;66;03m# raise original `AttributeError` if `attr` does not exist[39;00m
[0;32m---> 51[0m     [38;5;28mgetattr[39m([38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_final_estimator[49m, attr)
[1;32m     52[0m     [38;5;28;01mreturn[39;00m [38;5;28;01mTrue[39;00m

File [0;32m/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/pipeline.py:336[0m, in [0;36mPipeline._final_estimator[0;34m(self)[0m
[1;32m    335[0m [38;5;28;01mtry[39;00m:
[0;32m--> 336[0m     estimator [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43msteps[49m[43m[[49m[38;5;241;43m-[39;49m[38;5;241;43m1[39;49m[43m][49m[43m[[49m[38;5;241;43m1[39;49m[43m][49m
[1;32m    337[0m     [38;5;28;01mreturn[39;00m [38;5;124m"[39m[38;5;124mpassthrough[39m[38;5;124m"[39m [38;5;28;01mif[39;00m estimator [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m [38;5;28;01melse[39;00m estimator

[0;31mIndexError[0m: tuple index out of range

The above exception was the direct cause of the following exception:

[0;31mAttributeError[0m        Traceback (most recent call last)
Cell [0;32mIn[59], line 2[0m
[1;32m      1[0m [38;5;66;03m# score on train and test[39;00m
[0;32m----> 2[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m'[39m[38;5;124mTrain Score: [39m[38;5;132;01m{[39;00m[43mpipe[49m[38;5;241;43m.[39;49m[43mscore[49m(X_train,[38;5;250m [39my_train)[38;5;132;01m}[39;00m[38;5;124m'[39m)
[1;32m      3[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m'[39m[38;5;124mTest Score: [39m[38;5;132;01m{[39;00mpipe[38;5;241m.[39mscore(X_test,[38;5;250m [39my_test)[38;5;132;01m}[39;00m[38;5;124m'[39m)

File [0;32m/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/utils/_available_if.py:40[0m, in [0;36m_AvailableIfDescriptor.__get__[0;34m(self, obj, owner)[0m
[1;32m     36[0m [38;5;28;01mdef[39;00m [38;5;21m__get__[39m([38;5;28mself[39m, obj, owner[38;5;241m=[39m[38;5;28;01mNone[39;00m):
[1;32m     37[0m     [38;5;28;01mif[39;00m obj [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m     38[0m         [38;5;66;03m# delegate only on instances, not the classes.[39;00m
[1;32m     39[0m         [38;5;66;03m# this is to allow access to the docstrings.[39;00m
[0;32m---> 40[0m         [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_check[49m[43m([49m[43mobj[49m[43m,[49m[43m [49m[43mowner[49m[38;5;241;43m=[39;49m[43mowner[49m[43m)[49m
[1;32m     41[0m         out [38;5;241m=[39m MethodType([38;5;28mself[39m[38;5;241m.[39mfn, obj)
[1;32m     43[0m     [38;5;28;01melse[39;00m:
[1;32m     44[0m         [38;5;66;03m# This makes it possible to use the decorated method as an unbound method,[39;00m
[1;32m     45[0m         [38;5;66;03m# for instance when monkeypatching.[39;00m

File [0;32m/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/utils/_available_if.py:31[0m, in [0;36m_AvailableIfDescriptor._check[0;34m(self, obj, owner)[0m
[1;32m     29[0m     check_result [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mcheck(obj)
[1;32m     30[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m [38;5;28;01mas[39;00m e:
[0;32m---> 31[0m     [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m(attr_err_msg) [38;5;28;01mfrom[39;00m [38;5;21;01me[39;00m
[1;32m     33[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m check_result:
[1;32m     34[0m     [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m(attr_err_msg)

[0;31mAttributeError[0m: This 'Pipeline' has no attribute 'score'

